djangoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("listings.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

listings/urls.py
from django.urls import path
from . import views

app_name = "listings"

urlpatterns = [
    path("", views.index, name="index"),
    path("all_listings/", views.all_listings, name="all_listings"),
    path("new_listing/", views.new_listing, name="new_listing"),
    path("all_listings/<detail_id>", views.detail, name="detail"),
    path("my_listings/", views.my_listings, name="my_listings"),
    path("edit_listing/<edit_id>", views.edit_listing, name="edit_listing"),
    path("delete_listing/<delete_id>", views.delete_listing, name="delete_listing"),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("log_out/", views.log_out, name="log_out"),
    path("register/", views.register, name="register"),
]

listings/models.py
from django.db import models
from django.utils.timezone import now
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class Listings(models.Model):
    class SaleType(models.TextChoices):
        PICK_UP = "available for pickup"
        SHIP = "Available for shipping"

    class ConditionType(models.TextChoices):
        USED = "used"
        NEW = "New"

    class ProductType(models.TextChoices):
        BIKE = "Bike"
        PARTS = "Parts"
        OTHER = "Other"

    # CASCADE ensures that when a user is removed, so is the data associated with them
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)

    condition = models.CharField(
        max_length=50, choices=ConditionType.choices, default=ConditionType.USED
    )

    product_type = models.CharField(
        max_length=50, choices=ProductType.choices, default=ProductType.PARTS
    )

    sales_type = models.CharField(
        max_length=50, choices=SaleType.choices, default=SaleType.SHIP
    )

    price = models.FloatField()
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=100)
    main_photo = models.ImageField()
    photo_1 = models.ImageField()
    photo_2 = models.ImageField(blank=True)
    list_date = models.DateTimeField(default=now)
    contact_email = models.CharField(max_length=50)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

listings/views.py
from listings.filters import ListingFilter
from django.shortcuts import redirect, render
from .form import ListingForm
from .models import Listings
from .filters import ListingFilter


def index(req):
    return render(req, "listings/index.html")


def all_listings(req):
    all_listings = Listings.objects.order_by("-list_date")
    my_Filter = ListingFilter(req.GET, queryset=all_listings)
    all_listings = my_Filter.qs

    context = {"all_listings": all_listings, "my_Filter": my_Filter}
    return render(req, "listings/all_listings.html", context)


def new_listing(req):
    # use != to get empty form
    if req.method != "POST":
        form = ListingForm()
    else:
        # form w/ data from user
        form = ListingForm(req.POST, req.FILES)
        # check if is_valid against params in model
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = req.user
            instance.save()
            # go back to listings page after submition
            return redirect("listings:all_listings")

    context = {"form": form}
    return render(req, "listings/new_listing.html", context)


def detail(req, detail_id):
    detail = Listings.objects.get(id=detail_id)

    context = {"detail": detail}
    return render(req, "listings/detail.html", context)


def my_listings(req):
    my_listings = req.user.listings_set.order_by("-list_date")

    context = {"my_listings": my_listings}
    return render(req, "listings/my_listings.html", context)


def edit_listing(req, edit_id):
    listing = Listings.objects.get(id=edit_id)

    if req.method != "POST":
        form = ListingForm(instance=listing)
    else:
        form = ListingForm(req.POST, req.FILES, instance=listing)
        if form.is_valid():
            form.save()
            return redirect("listings:my_listings")

    context = {"listing": listing, "form": form}
    return render(req, "listings/edit_listing.html", context)


def delete_listing(req, delete_id):
    listing = Listings.objects.get(id=delete_id)

    if req.method == "POST":
        listing.delete()
        return redirect("listings:my_listings")

    context = {"listing": listing}
    return render(req, "listings/delete_listing.html", context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from .forms import UserForm


def log_out(req):
    logout(req)
    return redirect("listings:index")


def register(req):
    if req.method != "POST":
        form = UserForm()
    else:
        form = UserForm(data=req.POST)
        if form.is_valid():
            form.save()
            return redirect("users:login")

    context = {"form": form}
    return render(req, "registration/register.html", context)

listings/templates/listings/all_listings.html
{% extends "listings/base.html" %} {% block content %}

<h1>Listings</h1>

<div class="form-group">
    <div class="card">
        <form method="GET">
            <p><b>Condition:</b>{{ my_filter.form.condition }}</p>
            <p><b>State:</b>{{ my_filter.form.state }}</p>
            <p><b>City:</b>{{ my_filter.form.city }}</p>
            <button class="btn" type="submit">Search</button>
        </form>
    </div>
</div>
<br />
<br />

<div class="col">
    <div class="card">
        {% for listing in all_listings %}

        <img
            src="{{ listing.main_photo.url }}"
            width="300px"
            height="200px"
            alt="connect"
        />
        <img
            src="{{ listing.photo_1.url }}"
            width="300px"
            height="200px"
            alt="connect"
        />

        <p><b>Title:</b> {{ listing.title }}</p>
        <p><b>Condition:</b> {{ listing.condition }}</p>
        <p><b>Sale Type:</b> {{ listing.sale_type }}</p>
        <p><b>Price:</b> {{ listing.price|floatformat:2 }}</p>
        <p><b>Location:</b> {{ listing.city }}, {{ listing.state }}</p>
        <p><b>Post Date:</b> {{ listing.list_date }}</p>

        <ul>
            <a class="btn" href="{% url 'listings:detail' listing.id %}">
                View Listing
            </a>
        </ul>
        <hr />

        {% endfor %}
    </div>
</div>

{% endblock content %}

listings/templates/listings/base.html
<nav class="navbar">
    <!-- child templates -->
    <a href="{% url 'listings:index' %}">Bike Finder</a>
    <a href="{% url 'listings:all_listings' %}">Listings</a>
    <a href="{% url 'listings:new_listing' %}">New Listing</a>

    {% if user.is_authenticated %}
    <a href="{% url 'listings:my_listings' %}">My listings</a>
    {{ user.username }} -
    <a href="{% url 'users:log_out' %}">Logout</a>
    {% else %}
    <a href="{% url 'users:login' %}">Login</a>
    <a href="{% url 'users:register' %}">Register</a>
    {% endif %}
</nav>

<!-- empty block tags to be filled in from child templates -->
{% block content %} {% endblock content %}

listings/templates/listings/delete_listing.html
{% extends "listings/base.html" %}

{% block content %}

<div class="main">
    <form method="POST">
        <div class="container">
            {% csrf_token %}
            <h3>Do you want to delete <b>{{listing.title}}</b> listing ?</h3>
            <p>
                <input type="submit" class="btn" value="Delete" />
                <a class="btn"
                    href="{% url 'listings:my_listings'%}">Cancel
                </a>
            </p>
        </div>
    </form>
</div>

{% endblock content %}

listings/templates/listings/detail.html
{% extends 'listings/base.html' %}

{% block content %}

<div class="main">
    <h2>Listing:</h2>
    <p><b>Title: {{ detail.title }}</p>
    <p><b>Condition:</b> {{ detail.condition }}</p>
    <p><b>Product Type:</b> {{ detail.product_type }}</p>
    <p><b>Sale Type:</b> {{ detail.sale_type }}</p>
    <p><b>Price: $</b> {{ detail.price }}</p>
    <p><b>Location:</b> {{ detail.city }}, {{ detail.state }}</p>
    <p><b>Contact Email:</b> {{ detail.contact_email }}</p>
    <p><b>Post Date:</b> {{ detail.list_date }}</p>
    <p><b>Photos:</b></p>
    <img src="{{ detail.main_photo.url }}" width= 400px height=400px />
    <img src="{{ detail.photo_1.url }}" width= 400px height=400px />
    {% if detail.photo_2%}
    <img src="{{ detail.photo_2.url }}" width= 400px height=400px />
    {% endif %}

</div>

{% endblock content %}

listings/templates/listings/edit_listing.html
{% extends "listings/base.html" %}

{% block content %}

<h1>EDITING</h1>

<form action="{% url 'listings:edit_listing' listing.id %}"
    method='post' enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{ form.as_p }}
    </div>

    <button type="submit" class="btn">Edit listing
    </button>
</form>

{% endblock content %}

listings/templates/listings/index.html
{% extends "listings/base.html" %}
{% block content %}

<h3>Bike Finder</h3>

<p> it's a homepage</p>

{% endblock content %}

listings/templates/listings/my_listings.html
{% extends "listings/base.html" %}

{% block content %}

<h2>MY LISTINGS:</h2>

<div class="row">
    <div class="col">
        <div class="card">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Date Listed</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>

                {% for my_listing in my_listings %}

                <tr>
                    <td>{{ my_listing.title }}</td>
                    <td>{{ my_listing.list_date }}</td>
                    <td><a class="btn"
                            href="{% url 'listings:detail' my_listing.id %}">View
                        </a></td>
                    <td><a class="btn" href="{% url 'listings:edit_listing' my_listing.id %}">Edit</a></td>
                    <td><a class="btn" href="{% url 'listings:delete_listing' my_listing.id %}">Delete</a></td>
                </tr>

                {% endfor %}

            </table>
            <div class="container">
                <a class="btn"
                    href="{% url 'listings:new_listing'%}">New Listing
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

listings/templates/listings/new_listing.html
{% extends "listings/base.html" %}

{% block content %}

<h1>New Listing</h1>

<form action="{% url 'listings:new_listing' %}"
  method="POST"
  enctype="multipart/form-data">
  <div class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
  </div>
  <button type="submit" class="btn">
    Create Listing
  </button>
</form>

{% endblock content %}